name: otomadb-nicochuu-prod
version: "3.9"

services:
  nicochuu:
    build:
      context: ./.
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: postgresql://user:pass@postgres:5432/test
      SCRAPE_INTERVAL: 600
      SCRAPE_DURATION: 172800
      SCRAPE_TAGS: 音MAD
    ports:
      - target: 58080
        published: 58081
    depends_on:
      postgres:
        condition: service_healthy
      migration:
        condition: service_completed_successfully

  postgres:
    image: postgres:15@sha256:da76f1e3d9a1728600f062ba02d8e46b9c521012e87d402ce03e38ef0389979f
    healthcheck:
      test: pg_isready
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: test
    volumes:
      - type: volume
        source: postgres_data
        target: /var/lib/postgresql/data

  migration:
    build:
      context: ./.
      dockerfile: Dockerfile.migration
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql://user:pass@postgres:5432/test

volumes:
  postgres_data:
