name: Docker(nicochuu-migration)

on:
  push:
  pull_request:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Dockerfile.migration

      - uses: docker/setup-buildx-action@v2
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - id: image_tag
        name: Determine image tag
        uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
        with:
          result-encoding: string
          script: |
            if (context.eventName === "push" && context.ref.startsWith("refs/tags/v"))
              return context.ref.substring(11)
            else
              return "latest"
      - uses: docker/build-push-action@v4
        with:
          cache-from: type=gha
          cache-to: type=gha,mode=max
          context: .
          file: Dockerfile.migration
          push: ${{ steps.image_tag.outputs.result != 'latest' }}
          tags: ghcr.io/${{ github.repository_owner }}/nicochuu-migration:${{ steps.image_tag.outputs.result }}
